version: "3.9"
services:
  docker:

    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # aby se nemuselo neustale vystavovat znovu
    volumes:
      - ./:/code
      - ./data:/data
    mem_limit: 256m
