version: "3.9"
services:
  docker:

    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # aby se nemuselo neustale vystavovat znovu
    volumes:
      - ./:/code
      - ./data:/data
    mem_limit: 256m
    image: %env(DOCKER_REPO)%
    deploy:
      replicas: 1
    secrets:
      - my_secret

secrets:
  my_secret:
    file: ./my_secret.txt



