name: docker compose push
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login
        env: ${{ secrets.DOCKER_USER }}
        env: ${{ secrets.DOCKER_PASS }}
      - name: Docker build
        run: docker-compose build
      - name: docker push
        run: docker-compose push ${{ secrets.DOCKER_REPO }}

