name: docker compose push
on:
  tag:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v1
  - name: Docker login
    run: docker login -u ${{ secrets.DOCKER_USER }} -p {{ secrets.DOCKER_PASS }}
  - name: Docker build
    run: docker-compose build
  - name: docker push
    run: docker-compose push ${{ secrets.DOCKER_REPO }}

